// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using aLMS.Infrastructure.Common;

#nullable disable

namespace aLMS.Infrastructure.Migrations
{
    [DbContext(typeof(aLMSDbContext))]
    partial class aLMSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("aLMS.Domain.AccountEntity.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("aLMS.Domain.AnswerEntity.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AnswerContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("QuestionId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuestionId1");

                    b.ToTable("answer", (string)null);
                });

            modelBuilder.Entity("aLMS.Domain.BehaviourEntity.Behaviour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Video")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("UserId");

                    b.ToTable("behaviour", (string)null);
                });

            modelBuilder.Entity("aLMS.Domain.ClassEntity.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GradeId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex("GradeId1");

                    b.ToTable("class", (string)null);
                });

            modelBuilder.Entity("aLMS.Domain.DepartmentEntity.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("HeadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HeadId");

                    b.ToTable("department", (string)null);
                });

            modelBuilder.Entity("aLMS.Domain.ExerciseEntity.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ExerciseFile")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("HasTimeLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LessonId1")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionLayout")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("TimeLimit")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("LessonId1");

                    b.ToTable("exercise", (string)null);
                });

            modelBuilder.Entity("aLMS.Domain.GradeEntity.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SchoolId1")
                        .HasColumnType("uuid");

                    b.Property<string>("SchoolYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("SchoolId1");

                    b.ToTable("grade", (string)null);
                });

            modelBuilder.Entity("aLMS.Domain.LessonEntity.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TopicId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.HasIndex("TopicId1");

                    b.ToTable("lesson", (string)null);
                });

            modelBuilder.Entity("aLMS.Domain.ParentProfileEntity.ParentProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId");

                    b.HasIndex("StudentId");

                    b.ToTable("parent_profile", (string)null);
                });

            modelBuilder.Entity("aLMS.Domain.PermissionEntity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionName")
                        .IsUnique();

                    b.ToTable("permission", (string)null);
                });

            modelBuilder.Entity("aLMS.Domain.QuestionEntity.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExerciseId1")
                        .HasColumnType("uuid");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuestionImage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("ExerciseId1");

                    b.ToTable("question", (string)null);
                });

            modelBuilder.Entity("aLMS.Domain.RoleEntity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("aLMS.Domain.RolePermissionEntity.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PermissionId1")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RoleId1")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("PermissionId1");

                    b.HasIndex("RoleId1");

                    b.ToTable("role_permission", (string)null);
                });

            modelBuilder.Entity("aLMS.Domain.SchoolEntity.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.ToTable("school", (string)null);
                });

            modelBuilder.Entity("aLMS.Domain.StudentAnswerEntity.StudentAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AnswerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnswerId1")
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("QuestionId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentExerciseId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StudentExerciseId1")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("AnswerId1");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuestionId1");

                    b.HasIndex("StudentExerciseId");

                    b.HasIndex("StudentExerciseId1");

                    b.ToTable("student_answer", (string)null);
                });

            modelBuilder.Entity("aLMS.Domain.StudentExerciseEntity.StudentExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExerciseId1")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("ExerciseId1");

                    b.HasIndex("StudentId");

                    b.HasIndex("UserId");

                    b.ToTable("student_exercise", (string)null);
                });

            modelBuilder.Entity("aLMS.Domain.StudentProfileEntity.StudentProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EnrollDate")
                        .HasColumnType("date");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId");

                    b.HasIndex("ClassId");

                    b.HasIndex("SchoolId");

                    b.ToTable("student_profile", (string)null);
                });

            modelBuilder.Entity("aLMS.Domain.SubjectEntity.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClassId1")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("ClassId1");

                    b.ToTable("subject", (string)null);
                });

            modelBuilder.Entity("aLMS.Domain.TeacherProfileEntity.TeacherProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DepartmentId1")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("date");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DepartmentId1");

                    b.HasIndex("SchoolId");

                    b.ToTable("teacher_profile", (string)null);
                });

            modelBuilder.Entity("aLMS.Domain.TopicEntity.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("date");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("date");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubjectId1")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("SubjectId1");

                    b.ToTable("topic", (string)null);
                });

            modelBuilder.Entity("aLMS.Domain.UserEntity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("ParentProfileUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RoleId1")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SchoolId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentProfileUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherProfileUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ParentProfileUserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("RoleId1");

                    b.HasIndex("SchoolId");

                    b.HasIndex("SchoolId1");

                    b.HasIndex("StudentProfileUserId");

                    b.HasIndex("TeacherProfileUserId");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("aLMS.Domain.AnswerEntity.Answer", b =>
                {
                    b.HasOne("aLMS.Domain.QuestionEntity.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aLMS.Domain.QuestionEntity.Question", null)
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId1");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("aLMS.Domain.BehaviourEntity.Behaviour", b =>
                {
                    b.HasOne("aLMS.Domain.UserEntity.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aLMS.Domain.UserEntity.User", null)
                        .WithMany("Behaviours")
                        .HasForeignKey("UserId");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("aLMS.Domain.ClassEntity.Class", b =>
                {
                    b.HasOne("aLMS.Domain.GradeEntity.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aLMS.Domain.GradeEntity.Grade", null)
                        .WithMany("Classes")
                        .HasForeignKey("GradeId1");

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("aLMS.Domain.DepartmentEntity.Department", b =>
                {
                    b.HasOne("aLMS.Domain.UserEntity.User", "Head")
                        .WithMany()
                        .HasForeignKey("HeadId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Head");
                });

            modelBuilder.Entity("aLMS.Domain.ExerciseEntity.Exercise", b =>
                {
                    b.HasOne("aLMS.Domain.LessonEntity.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aLMS.Domain.LessonEntity.Lesson", null)
                        .WithMany("Exercises")
                        .HasForeignKey("LessonId1");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("aLMS.Domain.GradeEntity.Grade", b =>
                {
                    b.HasOne("aLMS.Domain.SchoolEntity.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aLMS.Domain.SchoolEntity.School", null)
                        .WithMany("Grades")
                        .HasForeignKey("SchoolId1");

                    b.Navigation("School");
                });

            modelBuilder.Entity("aLMS.Domain.LessonEntity.Lesson", b =>
                {
                    b.HasOne("aLMS.Domain.TopicEntity.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aLMS.Domain.TopicEntity.Topic", null)
                        .WithMany("Lessons")
                        .HasForeignKey("TopicId1");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("aLMS.Domain.ParentProfileEntity.ParentProfile", b =>
                {
                    b.HasOne("aLMS.Domain.UserEntity.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aLMS.Domain.UserEntity.User", "User")
                        .WithOne()
                        .HasForeignKey("aLMS.Domain.ParentProfileEntity.ParentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("User");
                });

            modelBuilder.Entity("aLMS.Domain.QuestionEntity.Question", b =>
                {
                    b.HasOne("aLMS.Domain.ExerciseEntity.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aLMS.Domain.ExerciseEntity.Exercise", null)
                        .WithMany("Questions")
                        .HasForeignKey("ExerciseId1");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("aLMS.Domain.RolePermissionEntity.RolePermission", b =>
                {
                    b.HasOne("aLMS.Domain.PermissionEntity.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aLMS.Domain.PermissionEntity.Permission", null)
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId1");

                    b.HasOne("aLMS.Domain.RoleEntity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aLMS.Domain.RoleEntity.Role", null)
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId1");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("aLMS.Domain.StudentAnswerEntity.StudentAnswer", b =>
                {
                    b.HasOne("aLMS.Domain.AnswerEntity.Answer", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("aLMS.Domain.AnswerEntity.Answer", null)
                        .WithMany("StudentAnswers")
                        .HasForeignKey("AnswerId1");

                    b.HasOne("aLMS.Domain.QuestionEntity.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aLMS.Domain.QuestionEntity.Question", null)
                        .WithMany("StudentAnswers")
                        .HasForeignKey("QuestionId1");

                    b.HasOne("aLMS.Domain.StudentExerciseEntity.StudentExercise", "StudentExercise")
                        .WithMany()
                        .HasForeignKey("StudentExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aLMS.Domain.StudentExerciseEntity.StudentExercise", null)
                        .WithMany("StudentAnswers")
                        .HasForeignKey("StudentExerciseId1");

                    b.Navigation("Answer");

                    b.Navigation("Question");

                    b.Navigation("StudentExercise");
                });

            modelBuilder.Entity("aLMS.Domain.StudentExerciseEntity.StudentExercise", b =>
                {
                    b.HasOne("aLMS.Domain.ExerciseEntity.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aLMS.Domain.ExerciseEntity.Exercise", null)
                        .WithMany("StudentExercises")
                        .HasForeignKey("ExerciseId1");

                    b.HasOne("aLMS.Domain.UserEntity.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aLMS.Domain.UserEntity.User", null)
                        .WithMany("StudentExercises")
                        .HasForeignKey("UserId");

                    b.Navigation("Exercise");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("aLMS.Domain.StudentProfileEntity.StudentProfile", b =>
                {
                    b.HasOne("aLMS.Domain.ClassEntity.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aLMS.Domain.SchoolEntity.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aLMS.Domain.UserEntity.User", "User")
                        .WithOne()
                        .HasForeignKey("aLMS.Domain.StudentProfileEntity.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("School");

                    b.Navigation("User");
                });

            modelBuilder.Entity("aLMS.Domain.SubjectEntity.Subject", b =>
                {
                    b.HasOne("aLMS.Domain.ClassEntity.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aLMS.Domain.ClassEntity.Class", null)
                        .WithMany("Subjects")
                        .HasForeignKey("ClassId1");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("aLMS.Domain.TeacherProfileEntity.TeacherProfile", b =>
                {
                    b.HasOne("aLMS.Domain.DepartmentEntity.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aLMS.Domain.DepartmentEntity.Department", null)
                        .WithMany("TeacherProfiles")
                        .HasForeignKey("DepartmentId1");

                    b.HasOne("aLMS.Domain.SchoolEntity.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aLMS.Domain.UserEntity.User", "User")
                        .WithOne()
                        .HasForeignKey("aLMS.Domain.TeacherProfileEntity.TeacherProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("School");

                    b.Navigation("User");
                });

            modelBuilder.Entity("aLMS.Domain.TopicEntity.Topic", b =>
                {
                    b.HasOne("aLMS.Domain.SubjectEntity.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aLMS.Domain.SubjectEntity.Subject", null)
                        .WithMany("Topics")
                        .HasForeignKey("SubjectId1");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("aLMS.Domain.UserEntity.User", b =>
                {
                    b.HasOne("aLMS.Domain.AccountEntity.Account", "Account")
                        .WithOne()
                        .HasForeignKey("aLMS.Domain.UserEntity.User", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("aLMS.Domain.ParentProfileEntity.ParentProfile", "ParentProfile")
                        .WithMany()
                        .HasForeignKey("ParentProfileUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aLMS.Domain.RoleEntity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("aLMS.Domain.RoleEntity.Role", null)
                        .WithMany("Users")
                        .HasForeignKey("RoleId1");

                    b.HasOne("aLMS.Domain.SchoolEntity.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("aLMS.Domain.SchoolEntity.School", null)
                        .WithMany("Users")
                        .HasForeignKey("SchoolId1");

                    b.HasOne("aLMS.Domain.StudentProfileEntity.StudentProfile", "StudentProfile")
                        .WithMany()
                        .HasForeignKey("StudentProfileUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aLMS.Domain.TeacherProfileEntity.TeacherProfile", "TeacherProfile")
                        .WithMany()
                        .HasForeignKey("TeacherProfileUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("ParentProfile");

                    b.Navigation("Role");

                    b.Navigation("School");

                    b.Navigation("StudentProfile");

                    b.Navigation("TeacherProfile");
                });

            modelBuilder.Entity("aLMS.Domain.AnswerEntity.Answer", b =>
                {
                    b.Navigation("StudentAnswers");
                });

            modelBuilder.Entity("aLMS.Domain.ClassEntity.Class", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("aLMS.Domain.DepartmentEntity.Department", b =>
                {
                    b.Navigation("TeacherProfiles");
                });

            modelBuilder.Entity("aLMS.Domain.ExerciseEntity.Exercise", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("StudentExercises");
                });

            modelBuilder.Entity("aLMS.Domain.GradeEntity.Grade", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("aLMS.Domain.LessonEntity.Lesson", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("aLMS.Domain.PermissionEntity.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("aLMS.Domain.QuestionEntity.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("StudentAnswers");
                });

            modelBuilder.Entity("aLMS.Domain.RoleEntity.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("aLMS.Domain.SchoolEntity.School", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("aLMS.Domain.StudentExerciseEntity.StudentExercise", b =>
                {
                    b.Navigation("StudentAnswers");
                });

            modelBuilder.Entity("aLMS.Domain.SubjectEntity.Subject", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("aLMS.Domain.TopicEntity.Topic", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("aLMS.Domain.UserEntity.User", b =>
                {
                    b.Navigation("Behaviours");

                    b.Navigation("StudentExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
